[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/go-chi/chi"
  branch = "master"

[[constraint]]
  name = "github.com/hybridgroup/mjpeg"
  branch = "master"
